DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  ID VARCHAR2(250) NOT NULL UNIQUE,
  NAME VARCHAR2(250) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PROVIDER VARCHAR2(250) NOT NULL,
  AVAILABLE BOOLEAN,
  MEASUREMENT_UNIT VARCHAR2(250),
  CREATED_DATETIME DATE,
  UPDATED_DATETIME DATE,
  LAST_UPDATED_REQUEST_TIMESTAMP NUMERIC(13,0),
  NUMBER_OF_TIMES_UPDATED NUMERIC(10,0)
);

DROP TABLE IF EXISTS DAILY_PRODUCT_INFORMATION;

CREATE VIEW DAILY_PRODUCT_INFORMATION
AS 
SELECT CREATED_DATETIME , NUMBER_OF_RECORD_CREATED , NUMBER_OF_RECORD_UPDATED 
FROM 
(SELECT CREATED_DATETIME, COUNT(*) AS NUMBER_OF_RECORD_CREATED FROM PRODUCT GROUP BY CREATED_DATETIME)  CREATE_DATE
JOIN
(SELECT UPDATED_DATETIME , COUNT(*) AS NUMBER_OF_RECORD_UPDATED FROM PRODUCT  GROUP BY UPDATED_DATETIME)  UPDATE_DATE
ON (CREATE_DATE.CREATED_DATETIME = UPDATE_DATE.UPDATED_DATETIME);
